onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/aclk}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/aresetn}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/srst}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awvalid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awready}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awaddr}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awlen}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awsize}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awburst}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awlock}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awcache}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awprot}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awqos}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awregion}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/awuser}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/wvalid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/wready}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/wlast}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/wdata}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/wstrb}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/wuser}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/bvalid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/bready}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/bid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/bresp}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/buser}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arvalid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arready}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/araddr}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arlen}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arsize}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arburst}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arlock}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arcache}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arprot}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arqos}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arregion}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/arid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/aruser}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/rvalid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/rready}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/rid}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/rresp}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/rdata}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/rlast}
add wave -noupdate -group {mst[0]} {/tb_top/mst[0]/ruser}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/aclk}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/aresetn}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/srst}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awvalid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awready}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awaddr}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awlen}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awsize}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awburst}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awlock}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awcache}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awprot}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awqos}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awregion}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/awuser}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/wvalid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/wready}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/wlast}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/wdata}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/wstrb}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/wuser}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/bvalid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/bready}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/bid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/bresp}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/buser}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arvalid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arready}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/araddr}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arlen}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arsize}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arburst}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arlock}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arcache}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arprot}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arqos}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arregion}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/arid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/aruser}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/rvalid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/rready}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/rid}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/rresp}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/rdata}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/rlast}
add wave -noupdate -group {mst[1]} {/tb_top/mst[1]/ruser}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/aclk}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/aresetn}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/srst}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awvalid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awready}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awaddr}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awlen}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awsize}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awburst}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awlock}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awcache}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awprot}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awqos}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awregion}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/awuser}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/wvalid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/wready}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/wlast}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/wdata}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/wstrb}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/wuser}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/bvalid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/bready}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/bid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/bresp}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/buser}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arvalid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arready}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/araddr}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arlen}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arsize}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arburst}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arlock}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arcache}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arprot}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arqos}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arregion}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/arid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/aruser}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/rvalid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/rready}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/rid}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/rresp}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/rdata}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/rlast}
add wave -noupdate -group {mst[2]} {/tb_top/mst[2]/ruser}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/aclk}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/aresetn}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/srst}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awvalid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awready}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awaddr}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awlen}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awsize}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awburst}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awlock}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awcache}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awprot}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awqos}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awregion}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/awuser}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/wvalid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/wready}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/wlast}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/wdata}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/wstrb}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/wuser}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/bvalid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/bready}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/bid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/bresp}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/buser}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arvalid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arready}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/araddr}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arlen}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arsize}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arburst}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arlock}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arcache}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arprot}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arqos}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arregion}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/arid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/aruser}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/rvalid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/rready}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/rid}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/rresp}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/rdata}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/rlast}
add wave -noupdate -group {mst[3]} {/tb_top/mst[3]/ruser}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/aclk}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/aresetn}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/srst}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awvalid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awready}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awaddr}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awlen}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awsize}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awburst}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awlock}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awcache}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awprot}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awqos}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awregion}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/awuser}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/wvalid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/wready}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/wlast}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/wdata}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/wstrb}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/wuser}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/bvalid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/bready}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/bid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/bresp}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/buser}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arvalid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arready}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/araddr}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arlen}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arsize}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arburst}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arlock}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arcache}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arprot}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arqos}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arregion}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/arid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/aruser}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/rvalid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/rready}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/rid}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/rresp}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/rdata}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/rlast}
add wave -noupdate -group {slv[0]} {/tb_top/slv[0]/ruser}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/aclk}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/aresetn}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/srst}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awvalid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awready}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awaddr}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awlen}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awsize}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awburst}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awlock}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awcache}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awprot}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awqos}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awregion}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/awuser}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/wvalid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/wready}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/wlast}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/wdata}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/wstrb}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/wuser}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/bvalid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/bready}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/bid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/bresp}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/buser}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arvalid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arready}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/araddr}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arlen}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arsize}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arburst}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arlock}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arcache}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arprot}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arqos}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arregion}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/arid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/aruser}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/rvalid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/rready}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/rid}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/rresp}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/rdata}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/rlast}
add wave -noupdate -group {slv[1]} {/tb_top/slv[1]/ruser}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/aclk}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/aresetn}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/srst}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awvalid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awready}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awaddr}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awlen}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awsize}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awburst}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awlock}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awcache}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awprot}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awqos}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awregion}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/awuser}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/wvalid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/wready}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/wlast}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/wdata}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/wstrb}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/wuser}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/bvalid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/bready}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/bid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/bresp}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/buser}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arvalid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arready}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/araddr}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arlen}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arsize}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arburst}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arlock}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arcache}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arprot}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arqos}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arregion}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/arid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/aruser}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/rvalid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/rready}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/rid}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/rresp}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/rdata}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/rlast}
add wave -noupdate -group {slv[2]} {/tb_top/slv[2]/ruser}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/aclk}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/aresetn}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/srst}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awvalid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awready}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awaddr}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awlen}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awsize}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awburst}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awlock}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awcache}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awprot}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awqos}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awregion}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/awuser}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/wvalid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/wready}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/wlast}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/wdata}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/wstrb}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/wuser}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/bvalid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/bready}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/bid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/bresp}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/buser}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arvalid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arready}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/araddr}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arlen}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arsize}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arburst}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arlock}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arcache}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arprot}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arqos}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arregion}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/arid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/aruser}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/rvalid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/rready}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/rid}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/rresp}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/rdata}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/rlast}
add wave -noupdate -group {slv[3]} {/tb_top/slv[3]/ruser}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {145000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 181
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {103756 ps} {230190 ps}
